Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_rng`` turned on.
#=========================== Test data ==========================#
test_data:  <torch.utils.data.dataloader.DataLoader object at 0x00000154CA5F3988>
RegressionModel(
  (embs): ModuleList(
    (0): Embedding(8, 4)
    (1): Embedding(14, 7)
    (2): Embedding(8, 4)
    (3): Embedding(14, 7)
    (4): Embedding(7, 3)
    (5): Embedding(6, 3)
    (6): Embedding(3, 1)
    (7): Embedding(14, 7)
  )
  (lins): ModuleList(
    (0): Linear(in_features=40, out_features=1000, bias=True)
    (1): Linear(in_features=1000, out_features=500, bias=True)
    (2): Linear(in_features=500, out_features=250, bias=True)
  )
  (bns): ModuleList(
    (0): GroupNorm(1, 1000, eps=1e-05, affine=True)
    (1): GroupNorm(1, 500, eps=1e-05, affine=True)
    (2): GroupNorm(1, 250, eps=1e-05, affine=True)
  )
  (outp): Linear(in_features=250, out_features=1, bias=True)
  (emb_drop): Dropout(p=0.04, inplace=False)
  (drops): ModuleList(
    (0): Dropout(p=0.001, inplace=False)
    (1): Dropout(p=0.01, inplace=False)
    (2): Dropout(p=0.01, inplace=False)
  )
  (bn): GroupNorm(1, 4, eps=1e-05, affine=True)
  (activation): Sigmoid()
) 


=== RUN # 0 ====================================

  0%|                                           | 0/2 [00:00<?, ?it/s]CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
 50%|█████████████████▌                 | 1/2 [00:03<00:03,  3.19s/it]grad and param do not obey the gradient layout contract. This is not an error, but may impair performance.
grad.sizes() = [3, 1], strides() = [1, 3]
param.sizes() = [3, 1], strides() = [1, 1] (Triggered internally at  ..\torch/csrc/autograd/functions/accumulate_grad.h:170.)
PrivacyEngine expected a batch of size 128 but the last step received a batch of size 98. This means that the privacy analysis will be a bit more pessimistic. You can set `drop_last = True` in your PyTorch dataloader to avoid this problem completely
100%|███████████████████████████████████| 2/2 [00:03<00:00,  2.41s/it]100%|███████████████████████████████████| 2/2 [00:03<00:00,  1.89s/it]
Train Epoch: 1 	Loss: 0.711783 (ε = 7.39, δ = 1e-05) for α = 4.4
  0%|                                           | 0/2 [00:00<?, ?it/s] 50%|█████████████████▌                 | 1/2 [00:00<00:00,  2.06it/s]100%|███████████████████████████████████| 2/2 [00:01<00:00,  1.98it/s]100%|███████████████████████████████████| 2/2 [00:01<00:00,  1.93it/s]
Train Epoch: 2 	Loss: 0.675151 (ε = 10.79, δ = 1e-05) for α = 3.4
size_average and reduce args will be deprecated, please use reduction='none' instead.
Traceback (most recent call last):
  File "main.py", line 330, in <module>
    main()
  File "main.py", line 267, in main
    fit = net.fit(X_cat, X_cont, y_true) #y labels) # X, y
  File "C:\Users\rapha\Documents\GitHub\bias-mitigation-sgd\model.py", line 112, in fit
    return super().fit(X, y)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 776, in fit_loop
    step_fn=self.train_step, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 812, in run_single_epoch
    step = step_fn(Xi, yi, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 709, in train_step
    self.optimizer_.step(step_fn)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\optim\adam.py", line 66, in step
    loss = closure()
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 705, in step_fn
    step = self.train_step_single(Xi, yi, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 645, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\skorch\net.py", line 1047, in infer
    return self.module_(**x_dict)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'X'
